include:
  - board: nice_nano_v2
    shield: corne_left
    cmake-args: >
      -DZMK_CONFIG=${{ github.workspace }}/config
    artifact-name: corne_left

  - board: nice_nano_v2
    shield: corne_right
    cmake-args: >
      -DZMK_CONFIG=${{ github.workspace }}/config
    artifact-name: corne_right
